/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

import classes.*;
import exceptions.NameNotUniqueException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author DAELN
 */
public class CadastroUsuarioGUI extends javax.swing.JFrame {

    UsuariosLista usuariosLista;
    CargosLista cargosLista;
    /**
     * Creates new form CadastroUsuarioGUI
     */
    public CadastroUsuarioGUI(UsuariosLista ul, CargosLista cl) {
        usuariosLista = ul;
        cargosLista = cl;
        
        initComponents();
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="My Init Codes">
    private void myInitComponents() {
        for (Cargo c : cargosLista.getCargos()) {
            combo_cargo.addItem(c.getNome());
        }
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtfd_nome = new javax.swing.JTextField();
        pass_senha = new javax.swing.JPasswordField();
        pass_senhaConfirm = new javax.swing.JPasswordField();
        combo_cargo = new javax.swing.JComboBox<>();
        lbl_nome = new javax.swing.JLabel();
        lbl_senha = new javax.swing.JLabel();
        lbl_senhaConfirm = new javax.swing.JLabel();
        lbl_cargo = new javax.swing.JLabel();
        btn_cadastrar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar novo usuário");
        setResizable(false);

        lbl_nome.setText("Nome de usuário:");

        lbl_senha.setText("Senha:");

        lbl_senhaConfirm.setText("Confirmar senha:");

        lbl_cargo.setText("Cargo:");

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nome)
                    .addComponent(lbl_cargo)
                    .addComponent(lbl_senha)
                    .addComponent(lbl_senhaConfirm)
                    .addComponent(btn_cancelar))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pass_senhaConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtfd_nome)
                    .addComponent(pass_senha)
                    .addComponent(btn_cadastrar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(combo_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txtfd_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_senha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_senhaConfirm)
                    .addComponent(pass_senhaConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cadastrar)
                    .addComponent(btn_cancelar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        String nomeUsuario = txtfd_nome.getText();
        String senha = String.valueOf(pass_senha.getPassword());
        String senhaConfirm = String.valueOf(pass_senhaConfirm.getPassword());
        String cargo = cargosLista.getCargos().get(combo_cargo.getSelectedIndex()).getNome();
        
        try {
            usuariosLista.addUsuario(nomeUsuario, senha, cargo);
        } catch (NameNotUniqueException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Usuário não é único", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JComboBox<String> combo_cargo;
    private javax.swing.JLabel lbl_cargo;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_senhaConfirm;
    private javax.swing.JPasswordField pass_senha;
    private javax.swing.JPasswordField pass_senhaConfirm;
    private javax.swing.JTextField txtfd_nome;
    // End of variables declaration//GEN-END:variables
}
