/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

import classes.*;
import exceptions.*;
import java.awt.Event;
import java.io.IOException;
import javax.swing.JOptionPane;
/**
 *
 * @author danil
 */
public class CadastroUsuarioDialogGUI extends javax.swing.JDialog {

    private Usuario usuario;
    private UsuariosLista usuariosLista;
    private CargosLista cargosLista;

    public CadastroUsuarioDialogGUI() {
    }
    /**
     * Creates new form CadastroUsuarioDialogGUI
     */
    public CadastroUsuarioDialogGUI(java.awt.Frame parent, boolean modal, CargosLista cargosLista) {
	super(parent, modal);
	usuariosLista = new UsuariosLista();
	this.cargosLista = cargosLista;
	initComponents();
	myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="My Init Codes">
    private void myInitComponents() {
        for (Cargo c : cargosLista.getCargos()) {
            combo_cargo.addItem(c.getNome());
        }
    }

    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nome = new javax.swing.JLabel();
        txtfd_nome = new javax.swing.JTextField();
        lbl_nomeUsuario = new javax.swing.JLabel();
        txtfd_nomeUsuario = new javax.swing.JTextField();
        lbl_cargo = new javax.swing.JLabel();
        combo_cargo = new javax.swing.JComboBox<String>();
        lbl_senha = new javax.swing.JLabel();
        pass_senha = new javax.swing.JPasswordField();
        lbl_senhaConfirm = new javax.swing.JLabel();
        pass_senhaConfirm = new javax.swing.JPasswordField();
        btn_cancelar = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_nome.setText("Nome:");

        lbl_nomeUsuario.setText("Nome de usuário:");

        lbl_cargo.setText("Cargo:");

        lbl_senha.setText("Senha:");

        lbl_senhaConfirm.setText("Confirmar senha:");

        pass_senhaConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pass_senhaConfirmKeyPressed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nomeUsuario)
                    .addComponent(lbl_cargo)
                    .addComponent(lbl_senha)
                    .addComponent(lbl_senhaConfirm)
                    .addComponent(btn_cancelar)
                    .addComponent(lbl_nome))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pass_senhaConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(pass_senha)
                            .addComponent(btn_cadastrar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(combo_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addComponent(txtfd_nomeUsuario)
                    .addComponent(txtfd_nome))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txtfd_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nomeUsuario)
                    .addComponent(txtfd_nomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_senha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_senhaConfirm)
                    .addComponent(pass_senhaConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cadastrar)
                    .addComponent(btn_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pass_senhaConfirmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_senhaConfirmKeyPressed
        if (evt.getKeyCode() == Event.ENTER) {
            btn_cadastrar.doClick();
        }
    }//GEN-LAST:event_pass_senhaConfirmKeyPressed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        String nomeUsuario = txtfd_nomeUsuario.getText();
        String nome = txtfd_nome.getText();
        String senha = String.valueOf(pass_senha.getPassword());
        String senhaConfirm = String.valueOf(pass_senhaConfirm.getPassword());
        String cargo = cargosLista.getCargos().get(combo_cargo.getSelectedIndex()).getNome();

        if (senha.equals(senhaConfirm)) {
            try {
                usuariosLista.addUsuario(nome, nomeUsuario, senha, cargo);
                JOptionPane.showMessageDialog(null, "Usuário adicionado com sucesso!");
                boolean success = true;
                try {
                    usuariosLista.gravarUsuariosArquivo();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Não foi possível gravar os usuários no arquivo, tente novamente", JOptionPane.ERROR_MESSAGE);
                    success = false;
                }
                if (success) {
                    this.dispose();
                }
            } catch (NameNotUniqueException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Usuário não é único", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Redigite a senha", "Senhas não são iguais", JOptionPane.WARNING_MESSAGE);
        }
	usuariosLista.close();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	}
	catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(CadastroUsuarioDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(CadastroUsuarioDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(CadastroUsuarioDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(CadastroUsuarioDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
        //</editor-fold>

	/* Create and display the dialog */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		CadastroUsuarioDialogGUI dialog = new CadastroUsuarioDialogGUI(new javax.swing.JFrame(), true, new CargosLista());
		dialog.addWindowListener(new java.awt.event.WindowAdapter() {
		    @Override
		    public void windowClosing(java.awt.event.WindowEvent e) {
			System.exit(0);
		    }
		});
		dialog.setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JComboBox<String> combo_cargo;
    private javax.swing.JLabel lbl_cargo;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_nomeUsuario;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_senhaConfirm;
    private javax.swing.JPasswordField pass_senha;
    private javax.swing.JPasswordField pass_senhaConfirm;
    private javax.swing.JTextField txtfd_nome;
    private javax.swing.JTextField txtfd_nomeUsuario;
    // End of variables declaration//GEN-END:variables
}
